project2DataWarehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: nicholasSirait21
      port: 5434
      dbname: postgres
      schema: data_warehouse
      threads: 1
